# Generated by Django 3.2.7 on 2021-09-24 08:02

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email_id', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('role_type', models.IntegerField(default=1)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='uploadedFileDetails',
            fields=[
                ('file_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('email_id', models.CharField(blank=True, max_length=100)),
                ('user_id', models.IntegerField(default=1)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_title', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.createuser')),
            ],
        ),
    ]
